import {
  TOKEN_PREVIEW_TYPES,
  type PaletteGroup,
  type TokenSection,
} from "@/features/token-docs/type";

export const paletteGroups: PaletteGroup[] = [
  {
    title: "Common",
    tones: [
      { label: "100", token: "common-100", value: "#FFFFFF" },
      { label: "0", token: "common-0", value: "#000000" },
    ],
  },
  {
    title: "Neutral",
    tones: [
      { label: "99", token: "neutral-99", value: "#F7F7F8" },
      { label: "95", token: "neutral-95", value: "#EFEFF1" },
      { label: "90", token: "neutral-90", value: "#E2E4E8" },
      { label: "80", token: "neutral-80", value: "#C8CCD3" },
      { label: "70", token: "neutral-70", value: "#A9AFB8" },
      { label: "60", token: "neutral-60", value: "#8C939E" },
      { label: "50", token: "neutral-50", value: "#6F7784" },
      { label: "40", token: "neutral-40", value: "#555D69" },
      { label: "30", token: "neutral-30", value: "#3D434C" },
      { label: "20", token: "neutral-20", value: "#292D33" },
      { label: "10", token: "neutral-10", value: "#17191D" },
      { label: "5", token: "neutral-5", value: "#0D0F12" },
    ],
  },
  {
    title: "Cool Neutral",
    tones: [
      { label: "99", token: "coolNeutral-99", value: "#F7F8FA" },
      { label: "97", token: "coolNeutral-97", value: "#EFF2F5" },
      { label: "95", token: "coolNeutral-95", value: "#E7EBF0" },
      { label: "90", token: "coolNeutral-90", value: "#D9E0E8" },
      { label: "80", token: "coolNeutral-80", value: "#BCC6D3" },
      { label: "70", token: "coolNeutral-70", value: "#9EABBC" },
      { label: "60", token: "coolNeutral-60", value: "#7F8FA3" },
      { label: "40", token: "coolNeutral-40", value: "#58677A" },
      { label: "30", token: "coolNeutral-30", value: "#44515F" },
      { label: "23", token: "coolNeutral-23", value: "#36414D" },
      { label: "20", token: "coolNeutral-20", value: "#2F3943" },
      { label: "10", token: "coolNeutral-10", value: "#1B2229" },
      { label: "5", token: "coolNeutral-5", value: "#0F1317" },
    ],
  },
  {
    title: "Blue Grey",
    tones: [
      { label: "99", token: "blueGrey-99", value: "#EDF2F5" },
      { label: "90", token: "blueGrey-90", value: "#D6E0E8" },
      { label: "80", token: "blueGrey-80", value: "#B8C6D3" },
      { label: "70", token: "blueGrey-70", value: "#99ACBD" },
      { label: "60", token: "blueGrey-60", value: "#7991A8" },
      { label: "50", token: "blueGrey-50", value: "#5D748A" },
      { label: "40", token: "blueGrey-40", value: "#4A5E73" },
      { label: "30", token: "blueGrey-30", value: "#37485C" },
      { label: "20", token: "blueGrey-20", value: "#263647" },
      { label: "10", token: "blueGrey-10", value: "#182532" },
    ],
  },
  {
    title: "Blue",
    tones: [
      { label: "99", token: "blue-99", value: "#F2F7FF" },
      { label: "95", token: "blue-95", value: "#E7F0FF" },
      { label: "90", token: "blue-90", value: "#D6E7FF" },
      { label: "80", token: "blue-80", value: "#ADCFFF" },
      { label: "70", token: "blue-70", value: "#7CB0FF" },
      { label: "60", token: "blue-60", value: "#4A90FF" },
      { label: "50", token: "blue-50", value: "#1A71FF", emphasized: true },
      { label: "40", token: "blue-40", value: "#0052CC" },
      { label: "30", token: "blue-30", value: "#003D99" },
      { label: "20", token: "blue-20", value: "#002B6B" },
      { label: "10", token: "blue-10", value: "#00153D" },
    ],
  },
  {
    title: "Red",
    tones: [
      { label: "99", token: "red-99", value: "#FFF3F2" },
      { label: "95", token: "red-95", value: "#FFE4E1" },
      { label: "90", token: "red-90", value: "#FFD2CC" },
      { label: "80", token: "red-80", value: "#FFAEA3" },
      { label: "70", token: "red-70", value: "#FF8776" },
      { label: "60", token: "red-60", value: "#FF5C47" },
      { label: "50", token: "red-50", value: "#F0442E", emphasized: true },
      { label: "40", token: "red-40", value: "#D92D20" },
      { label: "30", token: "red-30", value: "#B42318" },
      { label: "20", token: "red-20", value: "#8A140B" },
      { label: "10", token: "red-10", value: "#5C0B05" },
    ],
  },
  {
    title: "Green",
    tones: [
      { label: "99", token: "green-99", value: "#F4FBF6" },
      { label: "95", token: "green-95", value: "#EAF7EE" },
      { label: "90", token: "green-90", value: "#D6EFDD" },
      { label: "80", token: "green-80", value: "#AEDDAB" },
      { label: "70", token: "green-70", value: "#7BCB84" },
      { label: "60", token: "green-60", value: "#45B65C" },
      { label: "50", token: "green-50", value: "#16A34A" },
      { label: "40", token: "green-40", value: "#12803A" },
      { label: "30", token: "green-30", value: "#0D5C2A" },
      { label: "20", token: "green-20", value: "#083B1B" },
      { label: "10", token: "green-10", value: "#041F0E" },
    ],
  },
  {
    title: "Orange",
    tones: [
      { label: "99", token: "orange-99", value: "#FFF8EE" },
      { label: "95", token: "orange-95", value: "#FFF0DA" },
      { label: "90", token: "orange-90", value: "#FFE3B8" },
      { label: "80", token: "orange-80", value: "#FFD188" },
      { label: "70", token: "orange-70", value: "#FFBD54" },
      { label: "60", token: "orange-60", value: "#FFAB1F" },
      { label: "50", token: "orange-50", value: "#F89B00", emphasized: true },
      { label: "40", token: "orange-40", value: "#C97B00" },
      { label: "30", token: "orange-30", value: "#945A00" },
      { label: "20", token: "orange-20", value: "#633C00" },
      { label: "10", token: "orange-10", value: "#3A2300" },
    ],
  },
];

export const paletteSections: TokenSection[] = paletteGroups.map((group) => ({
  title: group.title,
  description: group.description,
  items: group.tones.map((tone) => ({
    name: tone.token,
    value: tone.value,
    description: tone.emphasized ? "Primary tone" : "Palette tone",
    previewType: TOKEN_PREVIEW_TYPES.COLOR,
  })),
}));
